name: codegen.yml
on:
  push:
    tags:
      - 'codegen-*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output tag version
        id: tag-version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/codegen-})"

      - name: Generate Code
        run: make gen
        shell: bash

      - name: Commit and push changes
        env:
          CODE_VERSION: ${{ steps.tag-version.outputs.version }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -am "Generated: ${{ env.CODE_VERSION }}"
            git push -u origin main
          fi