name: codegen.yml
on:
  push:
    tags:
      - 'codegen-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output tag version
        id: tag-version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/codegen-})"

      - name: Generate Code
        run: make gen
        shell: bash

      - name: Commit and push changes
        env:
          CODE_VERSION: ${{ steps.tag-version.outputs.version }}
          CURRENT_TIME: $(date -u +"%Y-%m-%dT%H:%M:%S")
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Generated: ${{ env.CODE_VERSION }} at ${{ env.CURRENT_TIME }}"
          git push -u origin main